# Generated by Django 4.2.5 on 2024-10-31 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('nivel_energia', models.CharField(choices=[('baja', 'Baja'), ('alta', 'Alta')], max_length=4)),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=6)),
                ('tamano', models.CharField(choices=[('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=7)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='perritos/')),
                ('es_adopcion_doble', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='refugio.perrito')),
            ],
        ),
    ]
