# Generated by Django 4.2.5 on 2024-10-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perritos',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
