# Generated by Django 4.2.5 on 2024-10-31 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refugio', '0002_alter_perrito_es_adopcion_doble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perrito',
            name='es_adopcion_doble',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='refugio.perrito'),
        ),
    ]
