# Generated by Django 4.2.5 on 2024-10-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugio', '0002_alter_perritos_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perritos',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
