# Generated by Django 4.2.5 on 2024-10-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugio', '0003_alter_perritos_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='perritos',
            name='tipo_casa',
            field=models.CharField(choices=[('Departamento', 'Departamento'), ('Casa', 'Casa'), ('Parcela', 'Parcela')], default='Departamento', max_length=20),
        ),
    ]
