# Generated by Django 4.2.5 on 2024-10-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugio', '0006_perritos_descripcion_alter_perritos_raza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('nivel_energia', models.CharField(choices=[('baja', 'Baja'), ('alta', 'Alta')], max_length=4)),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=6)),
                ('tamano', models.CharField(choices=[('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=7)),
                ('es_adopcion_doble', models.BooleanField(default=False)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='perritos/')),
            ],
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='perritos',
        ),
    ]
